# Default values for aivenator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/nais/aivenator/aivenator
  pullPolicy: Always
  tag: latest

resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 512Mi

extraEnv: {}
caBundle: false

clusterName: # Name of the cluster in NAIS convention

aiven:
  projects: # Space separated list of Aiven projects with Kafka clusters available for this aivenator instance
  mainProject: # Main Aiven project for services that only support one
  token: "" # API token for Aiven with access to above mentioned projects
  mainCidr: # CIDR for main Aiven project VPC
  cidrs: [] # List of additional CIDRs for other Aiven project VPCs

replicationConfig: false # Replicate common resources (e.g. NetworkPolicies) to all namespaces
