{{- if .Capabilities.APIVersions.Has "kyverno.io/v1" }}
{{- $valid := splitList " " .Values.aiven.projects }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-aivenator
  annotations:
    policies.kyverno.io/title: Validate fields for Aiven resources.
    policies.kyverno.io/category: Nais
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: AivenApplication, Application
    policies.kyverno.io/description: >-
      Validates that the fields for the given resources has allowed values.
      Currently only validates the kafka.pool field.
  labels:
    {{- include "aivenator.labels" . | nindent 4 }}
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 15
  rules:
    - name: "validate-kafka-pool"
      match:
        all:
          - resources:
              kinds:
                - aiven.nais.io/v1/AivenApplication
                - nais.io/v1alpha1/Application
              operations:
                - "CREATE"
                - "UPDATE"
      # only validate resources that have kafka.pool configured
      preconditions:
        all:
          - key: {{ "{{ request.object.spec.kafka.pool || '' }}" | quote }}
            operator: NotEquals
            value: ""
      validate:
        message: >-
          Kafka pool {{ "{{ request.object.spec.kafka.pool }}" | quote }} is not supported in this cluster.
          Allowed values: [{{ $valid | join ", " }}]

          See documentation: https://doc.nais.io/persistence/kafka/manage_topics/#creating-topics-and-defining-access
        deny:
          conditions:
            all:
              - key: {{ "{{ request.object.spec.kafka.pool }}" | quote }}
                operator: AnyNotIn
                value:
                  {{- range $valid }}
                  - {{ . | quote }}
                  {{- end }}
{{- end }}
