---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "aivenator.fullname" . }}
  labels:
    {{- include "aivenator.labels" . | nindent 4 }}
spec:
  groups:
    - name: aivenator
      rules:
        - alert: AivenatorIsSlow
          expr: 'histogram_quantile(0.95, sum(rate(aivenator_aiven_application_processing_time_seconds_bucket[5m])) by (le)) > 20'
          for: 10m
          labels:
            severity: critical
            feature: aivenator
            cluster: "{{ .Values.clusterName }}"
            namespace: nais-system
          annotations:
            summary: 95% of AivenApplications spend more than 20 seconds in processing for over 10 minutes.
            consequence: This will prevent applications from starting up, as the Pod will be stuck waiting on a secret to mount.
            action: |
              * Check Aiveantor dashboard for issues: https://monitoring.nais.io/d/aivenator/aivenator?orgId=1&refresh=1m&var-tenant={{ .Values.tenant }}&var-ds={{ .Values.tenant }}-{{ .Values.clusterName }}
              * Check aivenator logs: `kubectl logs --namespace nais-system deploy/aivenator -c aivenator`
              * Check for other Aiven problems:
                https://monitoring.nais.io/d/aiven-kafka-overview/aiven-kafka-overview?orgId=1&refresh=1m&var-tenant={{ .Values.tenant }}&var-ds={{ .Values.tenant }}-{{ .Values.clusterName }}
        - alert: AivenatorIsFailing
          expr: 'sum(rate(aivenator_aiven_applications_processed{synchronization_state="RolloutFailed"}[5m])) > 0'
          for: 10m
          labels:
            severity: critical
            feature: aivenator
            cluster: "{{ .Values.clusterName }}"
            namespace: nais-system
          annotations:
            summary: Aivenator has a higher than usual count of failed rollouts.
            consequence: This will prevent applications from starting up, as the Pod will be stuck waiting on a secret to mount.
            action: |
              * Check Aiveantor dashboard for issues: https://monitoring.nais.io/d/aivenator/aivenator?orgId=1&refresh=1m&var-tenant={{ .Values.tenant }}&var-ds={{ .Values.tenant }}-{{ .Values.clusterName }}
              * Check aivenator logs: `kubectl logs --namespace nais-system deploy/aivenator -c aivenator`
              * Check for other Aiven problems:
                https://monitoring.nais.io/d/aiven-kafka-overview/aiven-kafka-overview?orgId=1&refresh=1m&var-tenant={{ .Values.tenant }}&var-ds={{ .Values.tenant }}-{{ .Values.clusterName }}
        - alert: AivenServiceUserLimit
          expr: 'sum(aivenator_service_users_count{pool="{{ .Values.aiven.mainProject }}"}) >= ({{ .Values.aiven.serviceUserLimit }} - 100)'
          for: 5m
          labels:
            severity: critical
            feature: aivenator
            cluster: "{{ .Values.clusterName }}"
            namespace: nais-system
          annotations:
            summary: Approaching Aiven's Service Users limit
            consequence: Applications that use Aiven Kafka ({{ .Values.aiven.mainProject }}) will not be able to deploy new builds.
            description: |
              Approaching current limit of {{ .Values.aiven.serviceUserLimit }} Service Users in Aiven Kafka ({{ .Values.aiven.mainProject }}).

              Kafkarator allows applications to connect with Kafka topics through Service Users.
              Aivenator creates a new Service User whenever an application is deployed, and is responsible for deleting Service Users when they are no longer in use.

              Aiven maintains a limit on the number of Service Users per project, and there are less than 100 Service Users left before we hit the limit.

            action: |
              * Clean-up old Service Users by deleting unused `aiven-credentials` secrets
              * Contact Aiven and request extension of limit (afterwards remember to update configuration in fasit, and the dashboard below)

              Documentation: https://github.com/navikt/naisvakt/blob/master/kafka.md#g%C3%A5r-tom-for-kafka-service-users
              Instrumentation: https://monitoring.nais.io/d/aivenator/aivenator?orgId=1&refresh=1m&var-tenant={{ .Values.tenant }}&var-ds={{ .Values.tenant }}-{{ .Values.clusterName }}
