name: Build and deploy Aivenator
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths-ignore:
      - hack/**
      - charts/**
      - '*.md'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: aivenator
          google_service_account: gh-aivenator
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          multi-platform: true
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"

  deploy-fasit:
    name: Deploy to Fasit
    if: github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main'
    runs-on: fasit-deploy
    permissions:
      id-token: write
    needs:
      - build
    steps:
      - uses: nais/fasit-deploy@b2c0b6d049b53bef41b321eec406fe66938576fd # ratchet:nais/fasit-deploy@main
        with:
          json: '{"image": {"tag": "${{ needs.build.outputs.version }}"}}'
          feature_name: aivenator
